apiVersion: v1
kind: Pod
metadata:
  name: ci-default
  labels:
    scenario: default
spec:
  restartPolicy: Never
  containers:
  - name: target
    image: alpine:latest
    command: ["sleep", "3600"]
