apiVersion: v1
kind: Pod
metadata:
  name: ci-hardened
  labels:
    scenario: hardened
spec:
  restartPolicy: Never
  containers:
  - name: target
    image: alpine:latest
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
    volumeMounts:
    - name: tmp
      mountPath: /tmp
  volumes:
  - name: tmp
    emptyDir: {}
